# This is a basic workflow to help you get started with Actions
name: CI_Pull
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, Alpha, Beta, Experimental ]
    types: [ opened, reopened, edited, review_requested, synchronize ]
    paths:
    - 'metadata/**.xml'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install_utils
        run: sudo apt install libxml2-utils

      - name: get_changed_files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r  ...${{ github.event.after }})"
          echo "::set-output name=files1::$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.event.after }})"

      - name: echo_output
        run: |
          echo ${{ steps.getfile.outputs.files }}
          echo ${{ steps.getfile.outputs.files1 }}

      - name: check pr files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES

      - name: check xml files
        env:
          commit_sha: ${{ github.event.after }}
        run: |
          ls -l
          bash ./validate_xml.sh
          rc=$?
          exit $rc


